(deftheme eink
  "Eink Theme")
(let ((fg "#000000")
      (bg "#f9f9f9")
      (bg-light "#ddddd8")
      (fg-light "#ddddd8")
      (bg-highlight "yellow")
      (bg-highlight-2 "LightCyan")
      (bg-highlight-3 "LightGreen"))

  (custom-theme-set-faces
   'eink
   `(default ((t (:background ,bg :foreground ,fg))))
   `(button ((t (:foreground ,fg :underline t))))
   `(cursor ((t (:background ,fg :foreground ,bg))))
   `(custom-variable-tag ((t (:foreground ,fg))))
   `(default-italic ((t (:italic t))))
   `(font-lock-builtin-face ((t (:background ,bg :foreground "burlywood4"))))
   `(font-lock-comment-delimiter-face ((t (:foreground "#778899"))))
   `(font-lock-comment-face ((t (:foreground "#778899"))))
   `(font-lock-constant-face ((t (:foreground "#006565"))))
   `(font-lock-doc-face ((t (:foreground "#778899"))))
   `(font-lock-function-name-face ((t (:foreground "mediumblue"))))
   ;;`(font-lock-function-name-face ((t (:foreground "#6f42c1"))))
   `(font-lock-keyword-face ((t (:foreground "#a71d5d"))))
   ;;`(font-lock-keyword-face ((t (:foreground ,fg))))
   `(font-lock-preprocessor-face ((t (:foreground ,fg))))
   `(font-lock-reference-face ((t (:foreground ,fg))))
   `(font-lock-string-face ((t (:foreground "#778899"))))
   `(font-lock-type-face ((t (:foreground "springgreen4"))))
   `(font-lock-variable-name-face ((t (:foreground "green4" :underline nil))))
   `(font-lock-warning-face ((t (:foreground "red"))))
   `(fringe ((t (:background ,bg :foreground ,bg))))
   `(highlight ((t (:background "#CCEECC" :foreground ,fg))))
   `(ido-first-match ((t (:foreground ,fg))))
   `(ido-only-match ((t (:foreground ,fg))))
   `(ido-subdir ((t (:foreground ,fg))))
   `(isearch ((t (:background "yellow" :foreground ,fg))))
   `(link ((t (:foreground "medium blue" :underline t))))
   `(minibuffer-prompt ((t (:foreground ,fg :weight bold))))
   `(region ((t (:background "#CCEECC" :foreground ,fg))))
   `(whitespace-line ((t (:background ,bg-highlight-2 :foreground ,fg))))
   `(org-agenda-date ((t (:foreground "medium blue" :background ,bg :height 1.0))))
   `(org-agenda-date-today ((t (:foreground ,fg :background "green" :weight bold :height 1.0))))
   `(org-agenda-date-weekend ((t (:foreground ,fg :weight normal))))
   `(org-agenda-structure ((t (:foreground ,fg :weight bold))))
   `(org-block ((t (:foreground ,fg))))
   `(org-block-begin-line ((t (:foreground "grey70"))))
   `(org-block-end-line ((t (:foreground "grey70"))))
   `(org-date ((t (:foreground ,fg) :underline)))
   `(org-todo ((t (:foreground "tan4" :bold t))))
   `(org-done ((t (:foreground "springgreen4" :bold t))))
   `(org-hide ((t (:foreground ,bg))))
   `(org-level-1 ((t (:foreground "black" :height 1.0 :bold t))))
   `(org-level-2 ((t (:foreground "mediumblue"))))
   `(org-level-3 ((t (:foreground "tan4"))))
   `(org-level-4 ((t (:foreground "green4"))))
   `(org-level-5 ((t (:foreground ,fg))))
   `(org-link ((t (:foreground "medium blue" :underline t))))
   `(org-quote ((t (:foreground ,fg :slant italic :inherit org-block))))
   `(org-scheduled ((t (:foreground "medium blue"))))
   `(org-sexp-date ((t (:foreground ,fg))))
   `(org-tag ((t (:foreground "dark cyan"))))
   `(org-table ((t (:foreground "grey40" :height 1.0))))
   `(org-special-keyword ((t (:foreground "darkcyan" :family "sans noto" :height 1.0))))
   `(org-property-value ((t (:foreground ,fg :family "san noto" :height 1.0))))
   '(markdown-header-face-1 ((t (:foreground "blue" :height 1.3))))
   '(markdown-header-face-2 ((t (:foreground "blue"))))
   '(markdown-header-face-3 ((t (:foreground "black" :bold t))))
   `(magit-header ((t (:weight bold))))
   `(magit-item-mark ((t (:background ,bg-highlight))))
   `(magit-item-highlight ((t (:foreground "black" :background "yellow"))))
   `(magit-tag ((t (:foreground "black" :background "green"))))
   `(magit-section-heading ((t (:weight bold :height 1.2))))
   `(magit-section-highlight ((t (:inherit default))))
   `(magit-diff-context-highlight ((t (:weight bold))))
   `(magit-branch-local ((t (:weight bold))))
   `(magit-branch-remote ((t (:weight bold))))
   `(compilation-error ((t (:inherit error))))
   `(flycheck-error ((t (:inherit error))))
   `(flycheck-warning ((t (:inherit warning))))
   `(dired-directory ((t (:foreground "mediumblue"))))
   `(highlight ((t (:background "#CCEECC" :foreground ,fg))))
   `(highline-face ((t (:background "#CCEECC" :foreground ,fg))))
   `(comint-highlight-prompt ((t (:foreground "medium blue"))))
   `(company-echo-common ((t (:foreground ,fg))))
   `(company-tooltip-selection ((t (:background ,bg-highlight))))
   '(parenface-paren-face ((t (:foreground "gray70"))))
   '(parenface-curly-face ((t (:foreground "gray70"))))
   '(parenface-bracket-face ((t (:foreground "gray70"))))
   '(parenthesis ((t (:foreground "gray70"))))
   `(show-paren-match ((t (:foreground "black" :background "yellow"))))
   `(show-paren-mismatch ((t (:background "red" :foreground "black" :weight bold))))
   '(jabber-chat-prompt-foreign ((t (:foreground "#a71d5d"))))
   '(jabber-chat-prompt-local ((t (:foreground "mediumblue"))))
   '(jabber-chat-prompt-system ((t (:foreground "green"))))
   '(jabber-title-medium ((t (:height 1.5))))
   `(rainbow-delimiters-depth-1-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-2-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-3-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-4-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-5-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-6-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-7-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-8-face ((t (:foreground "grey60"))))
   `(rainbow-delimiters-depth-9-face ((t (:foreground "grey60"))))
   `(message-header-name ((t (:foreground "darkgreen"))))
   `(message-header-other ((t (:foreground "tan4"))))
   `(elfeed-search-feed-face ((t (:foreground "tan4"))))
   `(elfeed-search-title-face ((t (:foreground "black"))))
   `(elfeed-search-unread-title-face ((t (:foreground "medium blue"))))
   `(swoop-face-line-buffer-name ((t (:background "green" :foreground ,fg))))
   `(swoop-face-target-line ((t (:background "red" :foreground ,fg))))
   `(swoop-face-line-number ((t (:background "blue" :foreground ,fg))))
   `(swoop-face-header-format-line ((t (:background "brown" :foreground ,fg))))
   `(swoop-face-target-words ((t (:background "yellow" :foreground ,fg))))
   '(tuareg-font-lock-operator-face ((t :foreground "Grey50")))
   '(tuareg-font-double-colon-face ((t :foreground "Gray70")))
   '(tuareg-font-lock-extension-node-face ((t :foreground "grey20")))
   '(tuareg-font-lock-governing-face ((t :foreground "burlywood4")))
   `(persp-selected-face ((t (:foreground "green2"))))
   `(idle-highlight ((t (:background ,bg-highlight))))
   '(eval-sexp-fu-flash ((t (:foreground "gainsboro"))))
   '(variable-pitch ((t (:family "dejavu sans" :height 1.1))))
   `(cider-repl-err-output-face ((t (:weight bold :foreground "red"))))
   `(cider-result-overlay-face ((t (:weight bold))))))

(provide-theme 'eink)
